### PR TITLE
Modified "Percent change" into io_check script

### PR DESCRIPTION
**Pull request by TanZiTT**
Changed the "Change_Ratio" to "Percent_Change" and use the formula
Percent_Change = 100 \* (Modified_Output - Original_Output) /
Original_Output
Also, use "0.0000E+00" format for all of the numeric output to the
compare files.
"output_compare01.txt" and "output_compare02.txt" were the new outputs.

### CODE REVIEW

**Comment by kbrannan** [comment]
Looks good. I think this covers everything. Is there anything else you think we need to address?

**Comment by TanZiTT** [comment]
None that I can think of. But if there’s any modification you want in future (after Tuesday), I should be able to access the GitHub site and do some minor ones.

**Comment by kbrannan** [comment]
Great. Thanks for your work and best of luck on your defense!

**Comment by TanZiTT** [comment]
Thanks Kevin.
Looking forward to working with you in future!

**Pull request merged**
