### PR TITLE
Modified the io_check script, adding subwatershed as a input parameter

### PR DESCRIPTION
**Pull request by TanZiTT**
The io_check script can now output the comparison results for specified
subwatersheds. To batch the processes for multiple subwatersheds, using
the function like this:  "mapply(io_check, X,
ori.model.wrkdir,mod.model.wrkdir)". The X is a vector of subwatershed
IDs (e.g. 1:10)

### CODE REVIEW

**Comment by kbrannan** [comment]
Cool, I'll check it out

**Comment by kbrannan** [comment]
It look's great!
Could you change the "Change_Ratio" to "Percent_Change" and use the formula
Percent_Change = 100 \* (Modified_Output - Original_Output) / Original_Output

Also, could you use "0.0000E+00" format for all of the numeric output (including the Percent_Change) to the compare files.

**Comment by TanZiTT** [comment]
Sure, that should be easy fix. I will update the code this weekend.

**Comment by kbrannan** [comment]
Great! What is your last day of work?

**Comment by TanZiTT** [comment]
My last day of work is Tuesday, Nov 24th.

**Pull request merged**
