### PR TITLE
Add the script to compare output files between original submodels and modified submodels

### PR DESCRIPTION
**Pull request by TanZiTT**
io_check<-
function(ori.model.wrkdir,mod.model.wrkdir,output.compare.wrkdir=ori.model.wrkdir)
Load the function and two(three) arguments were needed,
"ori.model.wrkdir" is the path of the original model folder(one level
above 'sub-models'), "mod.model.wrkdir" is the path of the modified
model folder,  "output.compare.wrkdir" is an optional argument, with
default setting equals to "ori.model.wrkdir". This is the path where the
script saves the output comparison summary file.
The script will use the input files from subwatershed 01 from each
original sub-model,  run both original and modified sub-models and print
the output for each submodel to the corresponding original submodel
folder, and generate a text file named "output_compare.txt" which
includes the different variables for each sub-model.

### CODE REVIEW

**Comment by kbrannan** [comment]
looks good. You may want to think about breaking the script into some functions, but the script as it is now would be sufficient

**Comment by TanZiTT** [comment]
Morning Kevin,
Sorry for the late reply. I can only work 20hrs per week due to visa limitation, thus I am at TT office on Tuesday and Friday.
I have attached a sample output text file with this email.

Tan

**Comment by kbrannan** [comment]
Hi Tan, no problem. I think a simpler approach to the output comparison would work better. I suggest that the accum for each land use the source contributes to and the bacteria load to the stream from the source. Here are some examples.
cow-calf:
Bacteria.Instream
Accum.Pasture
Accum.Forest

on-site:
Accum.RAOCUT
bac.onsite.NearStrmStrctFailure.to.stream.load

beaver:
Accum.Forest
bac.total.in.stream

and so on. Once we look at these differences would could back tract within the sub-model out put to identify the key code changes that caused the differences.

Let me know what you think of this approach

**Comment by TanZiTT** [comment]
Hi Kevin,

I got your point.
So basically, you want to highlight the differences of outputs that are used to aggregate to the values in HSPF inputs, and then do the back track for each sub-model.
That’s a good idea. It will be really neat if we only output the key variables. I can modify the current script to only output the differences of key variables.
What’s your suggestion for the back-track step then, if we identified the different key variables? To run a function to show every different variable of that specific sub-model?

Tan

**Pull request merged**
