### PR TITLE
io_check modification

### PR DESCRIPTION
**Pull request by TanZiTT**
changed the io_check script to only output the key parameters. The
script now will run each sub-model (original and modified) and list all
the key parameters following by which parameter(s) is/are different for
each sub-model. The sample output text file ("output_compare.txt") is
uploaded.

### CODE REVIEW

**Comment by kbrannan** [comment]
Tan, I was away from my desk most of the week and will be oout the office tomorrow. I will check your updates the beginning of next week, thanks

**Comment by TanZiTT** [comment]
No problem, Kevin.

Anytime works for you.

**Comment by kbrannan** [comment]
Should I get the loads or percent change for the variables that are identified in io_check?

**Comment by TanZiTT** [comment]
En, good point.
Some of the variables are vectors, some are single elements. Let me think a little bit on how to format the output file.

**Pull request merged**
